<expression> : <expression> '+' <term>
             | <expression> '-' <term>
             | <term>

<term>       : <term> '*' <factor>
             | <term> '/' <factor>
             | <factor>

<factor>     : '-' <factor>
             | '+' <factor>
             | <primary>

<primary>    : NUMBER
             | '(' <expression> ')'
